[package]
name = "cmp6102"
version = "0.1.0"
authors = ["Tom Gardiner <Thomas.Gardiner3@mail.bcu.ac.uk>"]

[dependencies]
piston="^0.31.3"
piston_window = "^0.63.0"
conrod = { version = "^0.51.0", features = [ "piston" ] }
find_folder = "^0.3.0"
rand = "^0.3.15"
